import re

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Traducir los prints interactivos de autenticación y flujos principales
    translations = [
        ('"[+] Se detectó un Token guardado en el archivo .env. Usando token automáticamente..."', 
         '"[+] A saved Token was detected in the .env file. Using token automatically..."'),
        ('"=== MÉTODOS DE AUTENTICACIÓN HOTMART ==="', 
         '"=== HOTMART AUTHENTICATION METHODS ==="'),
        ('"1. Enviar Código/Token OTP a mi correo electrónico (Recomendado)"', 
         '"1. Send OTP Code/Token to my email address (Recommended)"'),
        ('"2. Pegar Bearer Token directamente desde el navegador (F12)"', 
         '"2. Paste Bearer Token directly from the browser (F12)"'),
        ('"3. Credenciales Usuario/Contraseña (Sparkle Legacy API)"', 
         '"3. User Credentials / Password (Sparkle Legacy API)"'),
        ('"Selecciona método (1, 2 o 3, por defecto 1): "', 
         '"Select auth method (1, 2 or 3, default 1): "'),
        ('"Ingresa tu correo electrónico registrado en Hotmart:\\n"', 
         '"Enter your registered Hotmart email:\\n"'),
        ('"¡Código enviado con éxito a "', 
         '"Verification code successfully sent to "'),
        ('"[AVISO] Estado HTTP "', 
         '"[WARNING] HTTP Status "'),
        ('"[AVISO] No se pudo solicitar automáticamente el código: "', 
         '"[WARNING] Could not automatically request verification code: "'),
        ('"\\nRevisa tu bandeja de entrada o spam en Hotmart."', 
         '"\\nCheck your inbox or spam in Hotmart."'),
        ('"Ingresa el código OTP (o el Bearer Token) recibido: "', 
         '"Enter the received OTP code (or Bearer Token): "'),
        ('"\\n¿Cómo obtener tu Token desde el navegador?"', 
         '"\\nHow to get your Token from the browser?"'),
        ('"1. Inicia sesión en tu curso en Hotmart desde Chrome/Firefox."', 
         '"1. Log in to your Hotmart course in Chrome/Firefox."'),
        ('"2. Presiona F12 -> pestaña \'Red\' (Network)."', 
         '"2. Press F12 -> \'Network\' tab."'),
        ('"3. Recarga la página o haz clic en una clase."', 
         '"3. Reload the page or click on any class."'),
        ('"4. Busca cualquier petición a \'api-club.hotmart.com\'."', 
         '"4. Search for any request to \'api-club.hotmart.com\'."'),
        ('"5. Copia el valor del encabezado \'authorization\' (Bearer eyJ...) o de \'token\'.\\n"', 
         '"5. Copy the value of the \'authorization\' header (Bearer eyJ...) or the \'token\'.\\n"'),
        ('"Pega tu Token aquí: "', 
         '"Paste your Token here: "'),
        ('"¿Cuál es el correo de inicio de sesión?\\n"', 
         '"What is your login email?\\n"'),
        ('"¿Cuál es la contraseña de inicio de sesión?\\n"', 
         '"What is your login password?\\n"'),
        ('"\\n[ERROR] Error al autenticar contra Hotmart (HTTP "', 
         '"\\n[ERROR] Error authenticating against Hotmart (HTTP "'),
        ('"Respuesta de la API: "', 
         '"API Response: "'),
        ('"\\nCorreo o contraseña inválidos o fallo de la API de Sparkle. Saliendo..."', 
         '"\\nInvalid email or password, or Sparkle API failure. Exiting..."'),
        ('"\\nAVISO: La API de Hotmart no devolvió cursos automáticamente."', 
         '"\\nWARNING: Hotmart API did not return courses automatically."'),
        ('"\\nSe encontraron "', 
         '"\\nFound "'),
        ('" curso(s) en el archivo config_cursos.py"', 
         '" course(s) in config_cursos.py file"'),
        ('"\\nAVISO: El archivo config_cursos.py está vacío."', 
         '"\\nWARNING: config_cursos.py file is empty."'),
        ('"\\nAVISO: Archivo config_cursos.py no encontrado."', 
         '"\\nWARNING: config_cursos.py file not found."'),
        ('"\\nAVISO: Error al cargar la configuración: "', 
         '"\\nWARNING: Error loading configuration: "'),
        ('"\\nPara encontrar el subdominio de tu curso:"', 
         '"\\nTo find your course subdomain:"'),
        ('"1. Accede a https://sun.hotmart.com/minhas-compras"', 
         '"1. Go to https://sun.hotmart.com/minhas-compras"'),
        ('"2. Haz clic en \'Acceder\' en el curso deseado"', 
         '"2. Click on \'Access\' in the desired course"'),
        ('"3. En la URL verás: https://hotmart.com/pt-br/club/SUBDOMINIO/..."', 
         '"3. Inside the URL you will see: https://hotmart.com/en/club/SUBDOMAIN/..."'),
        ('"4. El \'SUBDOMINIO\' es lo que debes ingresar"', 
         '"4. The \'SUBDOMAIN\' is the part to copy"'),
        ('"\\nConsejo: Edita el archivo \'config_cursos.py\' para guardar los subdominios permanentemente\\n"', 
         '"\\nTip: Edit \'config_cursos.py\' to save subdomains permanently\\n"'),
        ('"Ingresa el subdominio del curso (o presiona Enter para finalizar): "', 
         '"Enter the course subdomain (or press Enter to finish): "'),
        ('"AVISO: No se agregó ningún curso. Finalizando..."', 
         '"WARNING: No course was added. Exiting..."'),
        ('"Subdominio \'"', 
         '"Subdomain \'"'),
        ('"\' agregado\\n"', 
         '"\' added\\n"'),
        ('"\\n[ERROR] No se pudo conectar o validar la membresía para los subdominios ingresados."', 
         '"\\n[ERROR] Could not connect or validate membership for the provided subdomains."'),
        ('"Revisa tu Token o estado del curso."', 
         '"Please check your Token or course membership status."'),
        ('"Iniciando descarga del curso "', 
         '"Starting course download: "'),
        ('"\\n[ERROR] No se pudo obtener la lista de módulos (HTTP "', 
         '"\\n[ERROR] Could not obtain modules list (HTTP "'),
        ('"\\n[ERROR] La estructura devuelta por la API no contiene \'modules\'. Claves recibidas: "', 
         '"\\n[ERROR] The API response does not contain \'modules\'. Keys received: "'),
        ('"Diccionario creado con éxito, exportado como debug.txt"', 
         '"Dictionary created successfully, exported as debug.txt"'),
        ('"Total de clases en el curso "', 
         '"Total classes in the course "'),
        ('"MODO DE DESCARGA"', 
         '"DOWNLOAD MODE"'),
        ('"Lista de clases disponibles"', 
         '"Available classes list"'),
        ('"\\n[+] Iniciando descarga de la clase: \'"', 
         '"\\n[+] Starting download for class: \'"'),
        ('"\\nTotal de clases en el curso: "', 
         '"\\nTotal classes in the course: "'),
        ('"¿Desde qué número de clase empezar? (1 a "', 
         '"Start downloading from class number? (1 to "'),
        ('", o escribe \'exit\' para salir): "', 
         '", or type \'exit\' to quit): "'),
        ('"¿Hasta qué número de clase descargar? ("', 
         '"Download up to class number? ("'),
        ('"\\n[!] Opción no available. Por favor introduce un rango válido de clases."', 
         '"\\n[!] Option not available. Please enter a valid class range."'),
        ('"\\n[!] Opción no available. Introduce números válidos."', 
         '"\\n[!] Option not available. Please enter valid integers."'),
        ('"\\n[+] Seleccionado rango de clases del "', 
         '"\\n[+] Selected class range from "'),
        ('" al "', 
         '" to "'),
        ('"Verificando la clase\\n\\t "', 
         '"Verifying class\\n\\t "'),
        ('"Fallo al guardar la descripción de la clase "', 
         '"Failed to save class description for "'),
        ('"La clase no contiene videos de Hotmart en el reproductor nativo, buscando reproductores externos (Vimeo/YouTube)..."', 
         '"Class does not contain native Hotmart videos, checking external hosts (Vimeo/YouTube)..."'),
        ('"¡Vídeo de Vimeo encontrado! "', 
         '"Vimeo video found! "'),
        ('"WISTIA! Vídeo encontrado: "', 
         '"WISTIA! Video detected: "'),
        ('"¡Vídeo de YouTube encontrado! "', 
         '"YouTube video found! "'),
        ('"Descargando clase externa\\n\\t "', 
         '"Downloading external class\\n\\t "'),
        ('"Vídeo externo descargado con éxito."', 
         '"External video downloaded successfully."'),
        ('"Clase ya presente, omitiendo..."', 
         '"Class already exists, skipping..."'),
        ('"La plataforma no devolvió videos, verificar si es una publicación únicamente textual."', 
         '"No videos found on the platform, checking if it is a text-only class."'),
        ('"Intentando descargar clase de Hotmart\\n\\t "', 
         '"Attempting to download Hotmart class\\n\\t "'),
        ('"Intentando descargar la clase "', 
         '"Attempting to download class "'),
        ('"Video descargado con yt-dlp+cookies ("', 
         '"Video downloaded with yt-dlp+cookies ("'),
        ('"yt-dlp no descargó el archivo, intentando extracción manual de HLS..."', 
         '"yt-dlp did not download the file directly, attempting manual HLS extraction..."'),
        ('"No se obtuvo hls_url para videoHash="', 
         '"No hls_url retrieved for videoHash="'),
        ('"Todos los "', 
         '"All "'),
        ('" fragmentos HLS descargados correctamente"', 
         '" HLS segments downloaded successfully"'),
        ('"Llave de descifrado descargada correctamente"', 
         '"Decryption key downloaded successfully"'),
        ('"Ensamblando video .mp4..."', 
         '"Assembling .mp4 video..."'),
        ('"Video guardado ("', 
         '"Video saved ("'),
        ('"Carpeta temporal limpiada"', 
         '"Temporary folder cleared"'),
        ('"Error al procesar contenido de Google Drive: "', 
         '"Error processing Google Drive content: "'),
        ('"Guardando enlaces encontrados para la clase en\\n\\t "', 
         '"Saving complementary links to\\n\\t "'),
        ('"Enlaces detectados para la clase "', 
         '"Links detected for class "'),
        ('"Enlaces guardados con éxito"', 
         '"Links saved successfully"'),
        ('"Puedes definir tu correo y contraseña aquí si no deseas introducirlos por consola cada vez."', 
         '"You can define your email and password here if you do not want to enter them in the console each time."'),
    ]

    for orig, trans in translations:
        content = content.replace(orig, trans)

    # También traducir los comentarios de código más notables en las secciones modificadas
    content = re.sub(r'# Opciones de descarga:.*', '# Download options: Whole course, single class or custom range', content)
    content = re.sub(r'# Construir listado lineal.*', '# Build index list of all classes', content)
    content = re.sub(r'# Recorre cada módulo y clase.*', '# Iterate modules and classes to process downloads', content)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

if __name__ == '__main__':
    translate_file('hotmark.py')
    print("Translation completed successfully!")
